added files
iaroslav-eliseev/blog-customizer pull request #1
Opened 2024-09-01 10:10 UTC by iaroslav-eliseev

2024-09-01 18:49 UTC, SergeyK2004 requested changes
Добрый день! 

У вас получилась отличная работа:
* Почти полностью реализован функционал.
* Сайдбар закрывается по клику вне сайдбара
* Состояния страницы и формы разделены
* Обработчик события `submit` навешивается на форму, а не на клик по кнопке
* Типизированы все пропсы


Но есть пара моментов, который надо поправить:

- https://disk.yandex.ru/d/S_r5Vg_v6oMFkQ Отсутствует заголовок формы, уже писал вам об этом. На форме присутствуют лишние символы.
- Компонент страницы не должен знать про состояние формы. Состояние формы надо перенести в компонент `ArticleParamsForm`. Туда же нужно перенести все обработчики.
- Для дефолтных состояний статьи и формы используется `defaultArticleState`
- Для условного добавления стилей лучше воспользоваться библиотекой `clsx`.

Правки можно лучше остаются на ваше усмотрение:

- Обычно корневой `index.tsx` держат максимально компактным. Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.
- Обработчик клика по оверлею для закрытия сайдбара лучше попробовать реализовать через кастомный хук.
- Использовать один обработчик для событий `onChange` на элементах формы

Успешного рефакторинга!

2024-09-01 18:49 UTC, SergeyK2004 commented on src/components/article/Article.tsx
> +	opened?: () => void;
**Надо исправить:** 

Для реализации закрытия по клику вне сайдбара обработчик не должен передаваться в компонент статьи и использоваться там. Статья не должна ничего знать о том, что какому то другому компоненту в приложении нужно закрываться по клику на оверлей. Обработчик должен вешаться на `document` и проверяться, что клик произошел НЕ на DOM элементе сайдбара

2024-09-01 18:49 UTC, SergeyK2004 commented on src/components/arrow-button/ArrowButton.tsx
> +			className={`${styles.container} ${open &&styles.container_open}`}>
**Надо исправить:**

Для указания условия в стилях необходимо использовать библиотеку clsx.

2024-09-01 18:49 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	setArticleState: (articleState: ArticleStateType) => void
Надо исправить:
В компонент формы вам нужно передать только функцию изменения состояния setArticleState(), все остальное нужно убрать

2024-09-01 18:49 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const [fontFamilyOption, setFontFamilyOption] = useState<OptionType>(articleState.fontFamilyOption);
**Надо исправить:**

Настройки статьи по умолчанию описаны в объекте `defaultArticleState` в файле `constants/articleProps.ts`** стартеркита. В проекте нужно использовать значения из этого объекта как настройки по умолчанию, как для самой статьи, так и как начальные значения полей форм.

2024-09-01 18:49 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const [backgroundColor, setBackgroundColor] = useState<OptionType>(articleState.backgroundColor);
**Можно лучше:** 

Удобнее хранить все данные формы в одном стейте, а не создавать под каждое поле ввода свой стейт. Тогда единый обработчик для всех полей ввода будет выглядеть так:

```ts
const handleOnChange = (field: keyof ArticleStateType) => {
  return (value: OptionType) => {
    setState((prevState) => ({ ...prevState, [field]: value }));
  };
};
```

а его использование будет выглядеть так:

```ts
<Select
  title={'шрифт'}
  onChange={handleOnChange('fontFamilyOption')}
  selected={state.fontFamilyOption}
  options={fontFamilyOptions}
/>
```

2024-09-01 18:49 UTC, SergeyK2004 commented on src/components/article-params-form/ArticleParamsForm.tsx
> +				<form className={styles.form} onSubmit={handleSubmit}>
**Отлично:**

Отлично, что обработчик сохранения данных вызывается при отправке формы.

2024-09-01 18:49 UTC, SergeyK2004 commented on src/index.tsx
>  const App = () => {
**Можно лучше:**

Обычно корневой `index.tsx` держат максимально компактным. Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.

2024-09-01 18:49 UTC, SergeyK2004 commented on src/index.tsx
> +	const [open, setOpen] = useState(false);
**Надо исправить:**

Состояние открытия формы необходимо создавать и хранить в самой форме. Каждый компонент сам должен отвечать за хранение и обработку своего состояния. Использовать подъем состояния формы в родительский компонент не имеет смысла для нашего приложения. 

---

**Надо исправить:**

Обычно переменные, которые сохраняют булево значение начинаются с глагола `is` или `has`, например, `isOpen`

2024-09-01 18:49 UTC, SergeyK2004 commented on src/index.tsx
> +	function setArticleStateCallback(articleState: ArticleStateType) {
Надо исправить:
Не стоит создавать лишние сущности. Функция для вызова функции не имеет смысла.

2024-09-02 13:55 UTC, iaroslav-eliseev reviewed
Исправил все замечания.

2024-09-03 12:09 UTC, merged